### ISSUE TITLE
Typo in path (Dockerfile)

### ISSUE THREAD

**Issue by eflukx** [tiredofit/docker-osticket#12]
checkout path at 

https://github.com/tiredofit/docker-osticket/blob/528877343b53df3d3ae6b1d7a54573aeccb94404/Dockerfile#L57

should probably read

`/assets/install/include/plugins/archiver `

**Comment by tiredofit** [comment]
Thanks for this! Tagged and repackaged as `tiredofit/osticket:3.3.3`
