### ISSUE TITLE
Bootloop  in "Starting Zabbix Agent (classic) 5.4.9"

### ISSUE THREAD

**Issue by hugomon** [tiredofit/docker-osticket#17]
After starting the docker with docker-compose up -d, it never goes beyond that point, it continues indefinitely until I stop it manually.
The database does not have any table created.

<details><summary>Log</summary>
<p>

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] 00-functions: applying... 
> [fix-attrs.d] 00-functions: exited 0.
> [fix-attrs.d] 01-s6: applying... 
> [fix-attrs.d] 01-s6: exited 0.
> [fix-attrs.d] 02-zabbix: applying... 
> [fix-attrs.d] 02-zabbix: exited 0.
> [fix-attrs.d] 03-logrotate: applying... 
> [fix-attrs.d] 03-logrotate: exited 0.
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 00-startup: executing... 
> [cont-init.d] 00-startup: exited 0.
> [cont-init.d] 01-timezone: executing... 
> [cont-init.d] 01-timezone: exited 0.
> [cont-init.d] 02-permissions: executing... 
> [cont-init.d] 02-permissions: exited 0.
> [cont-init.d] 03-monitoring: executing... 
> 2022-01-14-09:43:31 [NOTICE] ** [monitoring] Container configured for monitoring with 'zabbix classic'
> [cont-init.d] 03-monitoring: exited 0.
> [cont-init.d] 04-scheduling: executing... 
> 2022-01-14-09:43:31 [NOTICE] ** [scheduling] Container configured for scheduled tasks with 'cron'
> [cont-init.d] 04-scheduling: exited 0.
> [cont-init.d] 05-logging: executing... 
> 2022-01-14-09:43:31 [NOTICE] ** [logging] Disabling Log Shipping Functionality
> [cont-init.d] 05-logging: exited 0.
> [cont-init.d] 06-messaging: executing... 
> 2022-01-14-09:43:31 [NOTICE] ** [messaging] Container configured to route mail via SMTP to 'smtp.gmail.com'
> [cont-init.d] 06-messaging: exited 0.
> [cont-init.d] 10-nginx: executing... 
> 2022-01-14-09:43:31 [NOTICE] ** [nginx] Disable Nginx FastCGI HTTPS Termination Support
> [cont-init.d] 10-nginx: exited 0.
> [cont-init.d] 11-nginx-config-reload: executing... 
> [cont-init.d] 11-nginx-config-reload: exited 0.
> [cont-init.d] 20-php-fpm: executing... 
> 2022-01-14-09:43:36 [ERROR] ** [php-fpm] Requested enabling openssl however it doesn't exist!
> 2022-01-14-09:43:37 [ERROR] ** [php-fpm] Requested enabling session however it doesn't exist!
> 2022-01-14-09:43:38 [NOTICE] ** [php-fpm] PHP-FPM Preparing to start with the following plugins enabled:  apcu bcmath bz2 ctype curl dom exif fileinfo gd iconv imap intl json ldap mbstring mysqli mysqlnd opcache pdo pdo_mysql pgsql phar simplexml tokenizer xml xmlreader xmlwriter
> [cont-init.d] 20-php-fpm: exited 0.
> [cont-init.d] 30-osticket: executing... 
> 2022-01-14-09:43:39 [NOTICE] ** [osticket] Applying configuration file security
> [cont-init.d] 30-osticket: exited 0.
> [cont-init.d] 99-container: executing... 
> [cont-init.d] 99-container: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 2022-01-14-09:43:40 [STARTING] ** [nginx] [1] Starting nginx 1.21.5
> 2022-01-14-09:43:40 [STARTING] ** [monitoring] [1] Starting Zabbix Agent (classic) 5.4.9
> 2022-01-14-09:43:40 [STARTING] ** [php-fpm] [1] Starting php-fpm 7.4.27
> 2022-01-14-09:43:40 [STARTING] ** [scheduling] [1] Starting cron
> 2022-01-14-09:43:41 [STARTING] ** [monitoring] [2] Starting Zabbix Agent (classic) 5.4.9
> 2022-01-14-09:43:42 [STARTING] ** [monitoring] [3] Starting Zabbix Agent (classic) 5.4.9
> 2022-01-14-09:43:43 [STARTING] ** [monitoring] [4] Starting Zabbix Agent (classic) 5.4.9
> 2022-01-14-09:43:44 [STARTING] ** [monitoring] [5] Starting Zabbix Agent (classic) 5.4.9
> 2022-01-14-09:43:45 [STARTING] ** [monitoring] [6] Starting Zabbix Agent (classic) 5.4.9
...
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] waiting for services.
> [cont-finish.d] done.
> [cont-finish.d] executing container finish scripts...
> basename: write error: Broken pipe

</p>
</details>

![imagen](https://user-images.githubusercontent.com/39093492/149497956-c0ab416d-e017-467b-9599-b94e0f15a0e8.png)

**Comment by tiredofit** [comment]
I'm going to issue a rebuild of the image (:latest) just to see if something has snuck in from one of the many base images I am using. Have a peek at this new image.

**Comment by hugomon** [comment]
> - CONTAINER_ENABLE_MONITORING=FALSE

That's the solution, thanks.
