### ISSUE TITLE
There is a problem with a time

### ISSUE THREAD

**Issue by Disinterpreter** [tiredofit/docker-osticket#2]
I'm not sure of depending it on your container. But when I installed it. I tried to reply to the message. And got this.

![image](https://user-images.githubusercontent.com/3816155/86468814-de19a280-bd40-11ea-8398-1c0a542f92fe.png)

Also: https://github.com/osTicket/osTicket/issues/3658

**Comment by tiredofit** [comment]
Hm - never seen this before. Do you have correct TIMEZONE environment variables set on all the containers?

**Comment by Disinterpreter** [comment]
> 
> 
> Hm - never seen this before. Do you have correct TIMEZONE environment variables set on all the containers?

I had default settings.

**Comment by tiredofit** [comment]
Try setting "TIMEZONE=(your Timezone ie America/Vancouver)" to match yours and things should sort itself out.
The images are defaulting to Etc/UTC now which may be causing your lock issues.
