### ISSUE TITLE
Latest OSTicket requires PHP8

### ISSUE THREAD

**Issue by codedmonkey** [tiredofit/docker-osticket#27]
Hello there!

Trying to install the latest version of this image (version 3.5.0) it fails to install OSTicket automatically. I simply get the message: "Support Ticket System Offline".

Manually activating the setup process reveals that the PHP version of the image (7.4.33) doesn't meet the requirements of the latest OSTicket version:
![Screenshot 2023-04-06 140916](https://user-images.githubusercontent.com/203651/230374819-50e01fc6-3341-4f59-9556-ddf74d2ad476.png)

Would it be possible to release a new version with a more recent version of PHP?

Thanks!

**Comment by tiredofit** [comment]
Sure thing! `3.5.1` now uses PHP 8.1
