### ISSUE TITLE
SMTP environmental variables

### ISSUE THREAD

**Issue by ukdanmc** [tiredofit/docker-osticket#30]
Hi,

I need to pass through some more SMTP environmental variables to get msmtprc working.
Specifically "auth on" and "tls_starttls on"

These are not listed as supported environmental variables in the documentation so how do I add these?

Thanks

**Comment by tiredofit** [comment]
Have a look at the [tiredofit/alpine](https://github.com/tiredofit/docker-alpine) base image for details on enabling those areas..

**Comment by ukdanmc** [comment]
Thank you Dave. Thats done it.
