### ISSUE TITLE
CRON_PERIOD or CRON_INTERVAL

### ISSUE THREAD

**Issue by MilorES** [tiredofit/docker-osticket#31]
Looking at the docker compose example it uses "CRON_PERIOD=10" but in the documentation it shows "CRON_INTERVAL"
Which one should I use?

Note: It may not be the site to thank but thank you, because it is very easy to get up and running.

**Comment by tiredofit** [comment]
Both work actually https://github.com/tiredofit/docker-osticket/blob/62400b5b9b3803eb07e29cb1ce7e5a6ae4230f8e/install/etc/cont-init.d/30-osticket#L24

I'd prefer long term usage of CRON_INTERVAL however. I've updated the example to reflect this..

**Comment by MilorES** [comment]
Thanks, I update my .yaml
