### ISSUE TITLE
Uptade 3.5.5 to latest

### ISSUE THREAD

**Issue by MilorES** [tiredofit/docker-osticket#42]
Do I have to do something special?

I updated the docker and it stopped working, I failed to connect to the BDD, a rollback, that is, going back to the previous version, fixed it.

**Comment by qman-being** [comment]
Same for me. 

I'm using Kubernetes instead for the image and I thought I was going mad when I could'nt get the container to connect to my MariaDB instance.

Specifying the 3.5.5 image from 2 months ago works

**Comment by miguelwill** [comment]
Hi,

I'm having the same problem. With version 3.5.5, everything works fine, but with the current "latest" version, it gets stuck in a loop showing the message that it can't connect to the database service.

At that point, I can access the container (also via Kubernetes), and it is able to resolve and connect to the database. Even using the MySQL CLI client, I can connect to the provided data, but it seems that the connection check script is not reading them correctly.

Do you have any idea why this could be?

Thanks,

**Comment by tiredofit** [comment]
There is a `3.5.6` and a `3.5.7` but they are just version bumps to OSTicket. I don't believe I have triggered any builds as of late to overwrite latest, so I'm not sure.

You could inspect the bad image and get me some details from the labels which would be useful.

Otherwise you could go into the bad image and type `head -v -n1 /assets/.changelogs/*` and get me the output as well..

Maybe Github went on the fritz..

**Comment by miguelwill** [comment]
hi
i run the image with the command "docker run --rm -it  tiredofit/osticket:latest /bin/bash" ,  and show this:

Image:  tiredofit/osticket | Version  3.5.5 Type 'image_changelog' for details
some logs...

[tiredofit/osticket:3.5.5 02:05:26 /assets/.changelogs] $ head -v -n1 /assets/.changelogs/*
==> /assets/.changelogs/tiredofit_docker-debian.md <==
## 7.8.6 2023-06-27 <dave at tiredofit dot ca>

==> /assets/.changelogs/tiredofit_docker-nginx-php-fpm.md <==
## 7.6.10 2023-07-06 <dave at tiredofit dot ca>

==> /assets/.changelogs/tiredofit_docker-nginx.md <==
## 6.3.4 2023-07-15 <dave at tiredofit dot ca>


[tiredofit/osticket:3.5.5 02:04:40 /assets/.changelogs] $ ls -lh
total 80K
-rw-r--r-- 1 root root  33K Jul 22 01:36 tiredofit_docker-debian.md
-rw-r--r-- 1 root root  20K Jul 22 09:12 tiredofit_docker-nginx-php-fpm.md
-rw-r--r-- 1 root root  20K Jul 22 06:23 tiredofit_docker-nginx.md
-rw-r--r-- 1 root root 3.5K Jul 24 17:13 tiredofit_docker-osticket.md



==> /assets/.changelogs/tiredofit_docker-osticket.md <==
## 3.5.5 2023-06-05 <dekat@github>

**Comment by miguelwill** [comment]
testing in image 3.5.7 , show error

```
2023-07-27.22:36:45 [WARN] ** [osticket] MySQL/MariaDB Server 'db-mariadb' is not accessible, retrying.. (5 seconds so far)
2023-07-27.22:36:50 [WARN] ** [osticket] MySQL/MariaDB Server 'db-mariadb' is not accessible, retrying.. (10 seconds so far)
2023-07-27.22:36:55 [WARN] ** [osticket] MySQL/MariaDB Server 'db-mariadb' is not accessible, retrying.. (15 seconds so far)
2023-07-27.22:37:00 [WARN] ** [osticket] MySQL/MariaDB Server 'db-mariadb' is not accessible, retrying.. (20 seconds so far)
2023-07-27.22:37:05 [WARN] ** [osticket] MySQL/MariaDB Server 'db-mariadb' is not accessible, retrying.. (25 seconds so far)
2023-07-27.22:37:10 [WARN] ** [osticket] MySQL/MariaDB Server 'db-mariadb' is not accessible, retrying.. (30 seconds so far)
```

with image 3.5.5,  work fine

```
** [osticket] Configuring mail settings
** [osticket] DB - Connecting to database mysql://osticket@db-mariadb/osticket
** [osticket] Database already installed
** [osticket] DB - Using installation secret from INSTALL_SECRET environmental variable
** [osticket] DB - Updating configuration file
2023-07-27.22:45:13 [NOTICE] ** [osticket] Applying configuration file security
2023-07-27.22:45:35 [STARTING] ** [nginx] [1] Starting nginx 1.25.0
2023-07-27.22:45:35 [STARTING] ** [php-fpm] [1] Starting php-fpm 8.1.18
```

**Comment by tiredofit** [comment]
Thanks.
Can you go inside the container again and give me the command of 
`mysql -u$DB_USER -p$DB_PASS -h$DB_HOST $DB_NAME`

**Comment by PaddyPat** [comment]
in app container:
bash: mysql: command not found

in db container:
/ # mysql -u$DB_USER -p$DB_PASS -h$DB_HOST $DB_NAME
ERROR 2005 (HY000): Unknown server host 'osticket' (-2)

**Comment by tiredofit** [comment]
`3.6.0` is building and it should resolve the issues with the mysql command being deprecarted from the MariaDB client. Let me know if this works for you.

**Comment by miguelwill** [comment]
hi

I just tested the new 3.6.0 image and it works correctly.

thanks

**Comment by PaddyPat** [comment]
Is 3.6.0 osticket 1.74? Or did I deploy wrong?
Thought it should be 1.8.0?

**Comment by tiredofit** [comment]
3.6.0 should be 1.18

**Comment by tiredofit** [comment]
As mentioned in another issue - Github has been stuck for the past little bit and it seems it's pushing false releases due to stuck PRs in the system which my upstream git server doesn't know about. Github tries to build the state at when the PR was submitted. This fix now will rebuild 3.5.6 3.5.7 and 3.6.0 properly.

**Comment by PaddyPat** [comment]
Docker image 3.6.1

[40] Starting nginx 1.25.1
osticket-app        | nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/osticket.conf:2
osticket-app        | 2023-07-30.06:14:06 [STARTING] ** [nginx] [41] Starting nginx 1.25.1
osticket-app        | nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/osticket.conf:2
osticket-app        | 2023-07-30.06:14:08 [STARTING] ** [nginx] [42] Starting nginx 1.25.1
osticket-app        | nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/osticket.conf:2
osticket-app        | 2023-07-30.06:14:09 [STARTING] ** [nginx] [43] Starting nginx 1.25.1
osticket-app        | nginx: [emerg] directive "listen" is not terminated by ";" in /etc/nginx/sites.enabled/osticket.conf:2
^Ccanceled

**Comment by MilorES** [comment]
What would be the procedure?
- For the service
- TAR of all files and folder
- Modify the Docker-Compose
- Update
So you could easily go back?

Note: I want to not have to start over or recover copy! :D
