### ISSUE TITLE
Docker compose dbbackup

### ISSUE THREAD

**Issue by PaddyPat** [tiredofit/docker-osticket#43]
Pls fix in db-backup

      - DB_PASSWORD=userpassword
      
To

      - DB_PASS=password

**Comment by AndrewPaglusch** [comment]
There's already a PR open for this: #39

**Comment by tiredofit** [comment]
Github doesnt play nice with my upstream git server when there is a GH PR available. I have closed any PRs and now my upstream git server should be able to update this version and the changes should reflect here.
