### ISSUE TITLE
Access denied using ADMIN_USER and ADMIN_PASS

### ISSUE THREAD

**Issue by mariomenjr** [tiredofit/docker-osticket#45]
I checked the closed issues and followed their suggestions. It's still not working for me.

I am setting up the system in my local environment. I changed the ADMIN_USER and ADMIN_PASS variables to dummy values, but it's not working.

![image](https://github.com/tiredofit/docker-osticket/assets/1946936/20dd9932-973c-41ee-8db7-0fb91d436574)

I also added the `ports` property, since I have something else running in port 80.

![image](https://github.com/tiredofit/docker-osticket/assets/1946936/d1478954-5f0f-4966-b7d1-1d65fd0ba215)

**Comment by radokristof** [comment]
You should login with admin credentials at `/scp`

**Comment by mariomenjr** [comment]
Thanks, that was it.
